# Generated by Django 4.2.3 on 2023-07-07 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.AddField(
            model_name='product',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category1', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient2', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient1', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient3', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient4', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient5', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient6', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient7', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient8', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient9', to='products.ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='products.category'),
        ),
    ]
